### ISSUE TITLE
버전 관리 error

### ISSUE THREAD

**Issue by Lay4U** [PinkWink/DataScience#71]
```
(base) C:\Windows\system32>conda env create --file pdj.yml

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Lay\Anaconda3\lib\site-packages\conda\exceptions.py", line 1003, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Lay\Anaconda3\lib\site-packages\conda_env\cli\main.py", line 73, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\Lay\Anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 77, in execute
        directory=os.getcwd())
      File "C:\Users\Lay\Anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 40, in detect
        if spec.can_handle():
      File "C:\Users\Lay\Anaconda3\lib\site-packages\conda_env\specs\yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "C:\Users\Lay\Anaconda3\lib\site-packages\conda_env\env.py", line 143, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "C:\Users\Lay\Anaconda3\lib\site-packages\conda_env\env.py", line 128, in from_yaml
        data = yaml_load_standard(yamlstr)
      File "C:\Users\Lay\Anaconda3\lib\site-packages\conda\common\serialize.py", line 76, in yaml_load_standard
        return yaml.load(string, Loader=yaml.Loader, version="1.2")
      File "C:\Users\Lay\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 640, in load
        return loader._constructor.get_single_data()  # type: ignore
      File "C:\Users\Lay\Anaconda3\lib\site-packages\ruamel_yaml\constructor.py", line 102, in get_single_data
        node = self.composer.get_single_node()
      File "C:\Users\Lay\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 75, in get_single_node
        document = self.compose_document()
      File "C:\Users\Lay\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 96, in compose_document
        node = self.compose_node(None, None)
      File "C:\Users\Lay\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 132, in compose_node
        node = self.compose_mapping_node(anchor)
      File "C:\Users\Lay\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 194, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
      File "C:\Users\Lay\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 130, in compose_node
        node = self.compose_sequence_node(anchor)
      File "C:\Users\Lay\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 162, in compose_sequence_node
        while not self.parser.check_event(SequenceEndEvent):
      File "C:\Users\Lay\Anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 144, in check_event
        self.current_event = self.state()
      File "C:\Users\Lay\Anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 500, in parse_block_sequence_entry
        token.id, token.start_mark)
    ruamel_yaml.parser.ParserError: while parsing a block collection
      in "<unicode string>", line 7, column 3:
          - ca-certificates=2017.08.26=ha1 ...
          ^ (line: 7)
    expected <block end>, but found '?'
      in "<unicode string>", line 261, column 3:
          prefix: C:\Users\Lay\Anaconda3
          ^ (line: 261)

`$ C:\Users\Lay\Anaconda3\Scripts\conda-env-script.py create --file pdj.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Users\Lay\Anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\Lay\Anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\Lay\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\Lay\Anaconda3\python.exe
               CONDA_ROOT=C:\Users\Lay\Anaconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\Lay
                     PATH=C:\Users\Lay\Anaconda3;C:\Users\Lay\Anaconda3\Library\mingw-w64\bin;C:
                          \Users\Lay\Anaconda3\Library\usr\bin;C:\Users\Lay\Anaconda3\Library\bi
                          n;C:\Users\Lay\Anaconda3\Scripts;C:\Users\Lay\Anaconda3\bin;C:\Users\L
                          ay\Anaconda3;C:\Users\Lay\Anaconda3\Library\mingw-w64\bin;C:\Users\Lay
                          \Anaconda3\Library\usr\bin;C:\Users\Lay\Anaconda3\Library\bin;C:\Users
                          \Lay\Anaconda3\Scripts;C:\Users\Lay\Anaconda3\bin;C:\Users\Lay\Anacond
                          a3\condabin;C:\Program Files (x86)\NAT Service;C:\Windows\system32;C:\
                          Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell
                          \v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA Nv
                          DLISR;C:\Users\Lay\Anaconda3;C:\Users\Lay\Anaconda3\Library\mingw-w64\
                          bin;C:\Users\Lay\Anaconda3\Library\usr\bin;C:\Users\Lay\Anaconda3\Libr
                          ary\bin;C:\Users\Lay\Anaconda3\Scripts;C:\Users\Lay\AppData\Local\Micr
                          osoft\WindowsApps;C:\Users\Lay\AppData\Local\Programs\Microsoft VS
                          Code\bin
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Users\Lay\Anaconda3
            shell level : 1
       user config file : C:\Users\Lay\.condarc
 populated config files :
          conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : C:\Users\Lay\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Lay\Anaconda3\pkgs
                          C:\Users\Lay\.conda\pkgs
                          C:\Users\Lay\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Lay\Anaconda3\envs
                          C:\Users\Lay\.conda\envs
                          C:\Users\Lay\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False
```

yml파일을 pdj로 바꿔서 실행했는데 에러가 나네요... 어디서 잘못된거죠?ㅜㅜ

**Comment by Lay4U** [comment]
pip requirements.txt로 다시한번 올려주실수있으신가요?
